- name: Install Java
  yum: name=java-1.8.0-openjdk-headless state=present

- name: Add elasticsearch repo key
  rpm_key:
    key: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Enable elasticsearch repo
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo

- name: Install elasticsearch
  yum: name=elasticsearch state=present

- name: Install elasticsearch config
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: Restart elasticsearch

- name: Configure elasticsearch system vars
  lineinfile:
    dest: /etc/sysconfig/elasticsearch
    regexp: "{{ item.name }}"
    line: "{{ item.name }}={{ item.value }}"
    create: yes
    state: present
    mode: 0644
  notify: Restart elasticsearch
  when: item.value
  with_items:
    - { name: ES_HEAP_SIZE,  value: "{{ es_heap_size }}"   }
    - { name: ES_JAVA_OPTS,  value: "{{ es_java_opts }}"   }

- name: Start elasticsearch
  service: name=elasticsearch state=started enabled=yes
